### ISSUE TITLE
Seeking for advice and suggestion on using MTKView

### ISSUE THREAD

**Issue by heng2j** [hanleyweng/iOS-ARKit-Headset-View#3]
Hi Hanley! 

Your work is fantastic! I learned a lot from your github repos! 

As you mentioned that to optimal performance, METAL should be used. And I am wondering if you can point us to the direction on how to use MTKView for the this stereoscopic views?

Currently, we need to access depth data to create depth images for depth image classification (with CoreML). So we use the MTKView as a previewView to show what the camera is seeing. It is working fine as a single view application. But what we are trying to achieve is having a to have stereoscopic views or triple views for headset view.  Since capturedDepthData for ARFrame only available on front-facing, depth-sensing camera so we probably can't use SceneKit to achieve the same as you shown from this repo.

I would like to seek for your advice. Any suggestion will help.

Thank you~
Heng

**Comment by hanleyweng** [comment]
Hi Heng,

Glad the repos have been helpful!

(Hoping I interpreted your question correctly.)

Unfortunately I don't know how to achieve what you're going for. You're correct that apple doesn't currently provide depth data for the backfacing iPhone Plus cameras. I'm also hoping Apple will open this up eventually. 

If you really want to use the rear depth cameras, for the time-being, I believe you'll lhave to forego ARKit for camera access and use AVFoundation instead. In that regard, you would loose the convenience of ARKit. Meaning any AR-related things you want to do would need to be custom-built for now.

Good luck!

Hanley

**Comment by heng2j** [comment]
Hi @hanleyweng, thank you so much for your feedback. And sorry for the late reply. And due to this issue. We have to moved on to another approach.
